project:
  type: website

website: 
  description: "통계와 AI를 기록하는 개인 블로그"
  site-url: https://shinjihan.github.io/studylog
  title: "StudyLog"
  favicon: favicon.png
  navbar:
    right:
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/SHINJIHAN
      - href: https://sinjihan71.tistory.com/
        text: '<img src="images/Tstory.png" style="width:15px;height:17px;">'

format:
  html:
    theme:
      - zephyr
    css: styles.css